version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: instimasterdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
